name = "MarkdownTables"
uuid = "1862ce21-31c7-451e-824c-f20fa3f90fa2"
authors = ["Tam√°s K. Papp <tkpapp@gmail.com>"]
version = "1.0"

[deps]
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
DisplayAs = "0b91fe84-8a4c-11e9-3e1d-67c38462b6d6"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
